services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - postgres
  postgres:
    image: postgres:16.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: farmers
    ports:
      - 5432:5432
